### ISSUE TITLE
Question about values

### ISSUE THREAD

**Issue by Dropsik** [yangosoft/dpf#1]
Hi. I ported yours code into Arduino and it works pretty well (but it's more dirty :) )
I can't figure, why I'm getting few values (and I'm not sure it's a problem with code or PIDs).

- turboPRESS always show value >=1.0 (even when engine is off, it showing 1.0)
- oilTemp show always -30 (even FIS showing >70)
and the bigger mess, is when I try call getSMC() - everywhere I got wrong values (like 2524 for RPM when I don't touch throttle) - for few second I see good values.
I'm working with Audi A4 B8 (CNHA engine)

**Comment by yangosoft** [comment]
Hi!

Check the data that you are getting. 

Print the bytes one to one and try to do the calculations by hand.

It could be also that your OBD2 dongle is not sending the data.

I'm not totally sure if B8  PIDs are different from B7 but at least the standard one must be the same.

BR,
yango

**Comment by Dropsik** [comment]
After few tests:
- oilTemp is not supported in my car
- getSMC() function retrieve correct value (checked with VCDS), but after call this funtion it's completly stop refreshing data.

**Comment by Dropsik** [comment]
Ok, I made a little debuging
getRpm();
getSpeed();
getBattery();
getTurboPressure();
getEngineLoad();
getEGT();
getCoolant();
works perfect and give reliable data until I call getSMC();
SEND_BLE("ATSH7E0\r"); cause that I got reliable data for DPF, but completly random for these above.

**Comment by yangosoft** [comment]
Make sure you only send ATSH7E0 once. This sets the ELM327 to use 7bits CAN messages, if I'm not wrong.

And remember to reset all stored values in ELM327.

**Comment by Dropsik** [comment]
I'm using initODB() from your code - so ATD is sent.
And funny thing - you send ATSH7E0 twice ;)
https://github.com/yangosoft/dpf/blob/master/src/dpf.cpp#L275
https://github.com/yangosoft/dpf/blob/master/src/dpf.cpp#L487

**Comment by Dropsik** [comment]
My source code:
https://github.com/Dropsik/dpf/blob/master/arduino/obd2/obd2.ino

**Comment by yangosoft** [comment]
@Dropsik did you manage to get fully working?

**Comment by Dropsik** [comment]
Unfortunately no.
I assume, that my elm327 adapter is ok (works with android app and show values). But I have no idea how to resolve problem

**Comment by Dropsik** [comment]
@yangosoft If you have any ideas or maybe the can try my code I'll be appreciated help.

**Comment by yangosoft** [comment]
Sadly I sold my nice car a few months ago and I don't have access to a CAGA engine.

Try to debug the Bluetooh traffic between an app and the device: https://stackoverflow.com/questions/23877761/sniffing-logging-your-own-android-bluetooth-traffic this should give you a hint about the correct sequence of commands.
